name: Release Windows

on:
  release:
    types:
      - created
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
          pkg-config
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-wget
          unzip
          wget
          curl

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Setup Python Dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install timeout_decorator numpy onnxruntime pytest opencv-python cmake

    - name: Checkout BMF repository
      run: |
        git clone https://github.com/JackLau1222/bmf.git
      shell: bash

    - name: Cache FFmpeg
      uses: actions/cache@v3
      with:
        path: ffmpeg-5.1.2-win64-gpl-shared
        key: ${{ runner.os }}-ffmpeg-5.1.2

    - name: Setup FFmpeg
      shell: pwsh
      run: |
        if (-not (Test-Path "ffmpeg-5.1.2-win64-gpl-shared")) {
          Invoke-WebRequest -Uri "https://github.com/GyanD/codexffmpeg/releases/download/5.1.2/ffmpeg-5.1.2-full_build-shared.7z" -OutFile "ffmpeg.7z"
          7z x ffmpeg.7z
          Rename-Item -Path "ffmpeg-5.1.2-full_build-shared" -NewName "ffmpeg-5.1.2-win64-gpl-shared"
          Remove-Item -Path "ffmpeg.7z"
        }
        $usrLocal = "C:\msys64\usr\local"
        if (-not (Test-Path $usrLocal)) {
          New-Item -Path $usrLocal -ItemType Directory -Force
        }
        Copy-Item -Path "ffmpeg-5.1.2-win64-gpl-shared\*" -Destination $usrLocal -Recurse -Force

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_qtcreator'
        cache: true

    - name: Build BMF
      shell: pwsh
      run: |
        cd bmf
        $env:PYTHONIOENCODING = "utf-8"
        
        $bashPath = "C:\msys64\usr\bin\bash.exe"
        $bashCommand = @'
        export PATH=/usr/bin:/usr/lib:/usr/local/bin:/usr/local/lib:$PATH
        python -V
        python3 -V
        echo $PATH
        eval "$(./win_env/vcvarsall.sh x64)"
        export INCLUDE="${INCLUDE};C:\\msys64\\usr\\local\\include"
        cmake -version
        ./build_win_lite.sh --msvc=2019 --preset=x64-Release bmf_ffmpeg
        cmake --build build_win_lite/x64-Release --config Release --target ALL_BUILD
        cp -r build_win_lite/x64-Release/output ..
'@
        
        $bashCommand | Out-File -FilePath "build_command.sh" -Encoding utf8 -NoNewline
        & $bashPath -l build_command.sh

    - name: Set Environment Variables
      shell: pwsh
      run: |
        $currentLocation = Get-Location
        "C_INCLUDE_PATH=$currentLocation\output\bmf\include" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "CPLUS_INCLUDE_PATH=$currentLocation\output\bmf\include" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "LIBRARY_PATH=$currentLocation\output\bmf\lib" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "PATH=$currentLocation\output\bmf\bin;$currentLocation\output\bmf\lib;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "PYTHONPATH=$currentLocation\output\bmf\lib;$currentLocation\output" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

    - name: Build Project
      shell: pwsh
      run: |
        mkdir -p src/build
        cd src
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release

    - name: Create Package
      shell: pwsh
      run: |
        mkdir -p OpenConverter_Windows_x64
        Copy-Item -Path "src\build\Release\*" -Destination "OpenConverter_Windows_x64" -Recurse -Force
        Copy-Item -Path "output\bmf\lib\*" -Destination "OpenConverter_Windows_x64" -Recurse -Force
        7z a OpenConverter_Windows_x64.zip OpenConverter_Windows_x64

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: OpenConverter_Windows_x64
        path: OpenConverter_Windows_x64.zip

    - name: Get Release Tag
      id: release_info
      run: echo "::set-output name=release_tag::$(echo ${GITHUB_REF#refs/tags/})"
      shell: bash

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: OpenConverter_Windows_x64.zip

    - name: Finish
      run: echo "Windows release complete" 